<a href="https://colab.research.google.com/github/KatherinePalaciosaCortez/datawarehouse_seguros/blob/main/Te_damos_la_bienvenida_a_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/KatherinePalaciosaCortez/datawarehouse_seguros.git

In [1]:
import pandas as pd

In [15]:
#ruta del dataset almacenado en git
url = "https://raw.githubusercontent.com/KatherinePalaciosaCortez/datawarehouse_seguros/refs/heads/main/clientes.csv"

In [11]:
df = pd.read_csv(url)
print("Dataset Cargado corrextamente")

Dataset Cargado corrextamente

In [12]:
display(df.head())

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

BLOQUE 2:Exploracion del DATASET

In [16]:
print("primeras filas del dataset")
display(df.head())

primeras filas del dataset

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [18]:
print("Disemensiones del dataset(filas,coloumnas)")
print(df.shape)

Disemensiones del dataset(filas,coloumnas)
(3030, 7)

In [19]:
print("columnas del dataset")
print(df.columns)

columnas del dataset
Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento'],
      dtype='object')

In [20]:
print("tipo de datos")
print(df.dtypes)

tipo de datos
id_cliente           int64
nombre              object
email               object
genero              object
fecha_nacimiento    object
ciudad              object
segmento            object
dtype: object

In [21]:
print("valorees nulos por columna")
print(df.isnull().sum())

valorees nulos por columna
id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [22]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
0

BLOQUE 3: LIMPIEZA DE DATOS

In [23]:
#ELIMINA ESPACIOS AL INICO Y AL FINAL E COLUMNAS DE TEXTO
for col in df.select_dtypes(include="object").columns:df[col]=df[col].str.strip()

In [25]:
#Normalizar el nombre
df["nombre"]=df["nombre"].str.title()

In [26]:
#Normalizar el email
df["email"]=df["email"].str.lower()

In [27]:
#Normalizar el genero
df["genero"]=df["genero"].str.upper()

In [33]:
#Convertir fecha de nacimiento a formato fecha
df['fecha_nacimiento']=pd.to_datetime(df['fecha_nacimiento'],errors="coerce")

In [29]:
#normalizar ciudad
df["ciudad"]=df['ciudad'].str.title()

In [35]:
#normalizar Ciudad
df['ciudad']=df['ciudad'].str.title()
df['ciudad']=df['ciudad'].astype(str)
df['ciudad']=df['ciudad'].str.upper()

In [30]:
#normalizar segmento
df['segmento']=df['segmento'].astype(str)
df['segmento']=df['segmento'].str.strip()
df['segmento']=df['segmento'].str.upper()

In [34]:
from os import EX_TEMPFAIL
from enum import nonmember
for col in df.columns: print(col)

id_cliente
nombre
email
genero
fecha_nacimiento
ciudad
segmento

BLOQUE 4: VALIDACION DE DATOS

In [39]:
#crear columna para registrar errores
df["motivo_rechazo"]=""

#validar id clientw
df.loc[df["id_cliente"].isnull(),"motivo_rechazo"]="id_cliente nulo;"